FROM gradle:6.6.1-jdk14
VOLUME /tmp
EXPOSE 8080
# ADD ../build/libs/marketplace-0.0.1-SNAPSHOT.jar marketplace.jar
# ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/.urandom", "-jar", "/marketplace.jar"]
